apiVersion: v1
kind: Service
metadata:
  name: task-manager-frontend
spec:
  selector:
    app: task-manager-frontend
  ports:
    - name: http                # <--- required
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend
spec:
  selector:
    app: task-manager-backend
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-mongo
spec:
  selector:
    app: task-manager-mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
