apiVersion: v1
kind: Service
metadata:
  name: task-manager-frontend
spec:
  selector:
    app: task-manager-frontend
  ports:
    - protocol: TCP
      port: 3000          # external port
      targetPort: 3000    # container port
  type: NodePort          # NodePort so we can access via Minikube IP or EC2 public IP

---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend
spec:
  selector:
    app: task-manager-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort          # same reason as frontend

---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-mongo
spec:
  selector:
    app: task-manager-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP         # MongoDB usually stays internal
